services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qbittorrent web interface
      - 6881:6881 # qbittorrent torrent port
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 9696:9696 # prowlarr
      - 6767:6767 # bazarr
      - 8191:8191 # flaresolverr
    volumes:
      - /docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=Poland
      - HEALTH_VPN_DURATION_INITIAL=120s
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy= "true"
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /docker/qbittorrent:/config
      - /media/torrents/downloads:/downloads
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: "service_healthy"
        restart: true
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Europe/Warsaw
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/prowlarr:/config
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: "service_healthy"
        restart: true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Europe/Warsaw
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/sonarr:/config
      - /media/torrents/downloads:/downloads
      - /media/torrents/tv:/TV
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: "service_healthy"
        restart: true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Europe/Warsaw
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/radarr:/config
      - /media/torrents/downloads:/downloads
      - /media/torrents/movies:/Movies
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: "service_healthy"
        restart: true

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Poland/Warsaw
    volumes:
      - /docker/bazarr/config:/config
      - /media/torrents/movies:/Movies
      - /media/torrents/tv:/TV
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: "service_healthy"
        restart: true

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /docker/homarr/configs:/app/data/configs
      - /docker/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '7575:7575'

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Poland/Warsaw
    ports:
      - '5055:5055'
    volumes:
      - /docker/jellyseerr/config:/app/config
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Poland/Warsaw
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: "service_healthy"
        restart: true